// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhY-qfnE4HgV1ZGNLjqecN7WpeE0uCEj8',
    appId: '1:495145618386:web:141f0bbf295583b23e160b',
    messagingSenderId: '495145618386',
    projectId: 'smart-64616',
    authDomain: 'smart-64616.firebaseapp.com',
    databaseURL: 'https://smart-64616-default-rtdb.firebaseio.com',
    storageBucket: 'smart-64616.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2UEWd6GobflhiSUcSeGd8ykTsZ9ZJg2k',
    appId: '1:495145618386:android:44f93d67ee2d52173e160b',
    messagingSenderId: '495145618386',
    projectId: 'smart-64616',
    databaseURL: 'https://smart-64616-default-rtdb.firebaseio.com',
    storageBucket: 'smart-64616.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUscPZY6ilgqMpjue7MmRdsctW04_WZWY',
    appId: '1:495145618386:ios:8c66e78ea79aff973e160b',
    messagingSenderId: '495145618386',
    projectId: 'smart-64616',
    databaseURL: 'https://smart-64616-default-rtdb.firebaseio.com',
    storageBucket: 'smart-64616.appspot.com',
    iosBundleId: 'com.example.smartsavior2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUscPZY6ilgqMpjue7MmRdsctW04_WZWY',
    appId: '1:495145618386:ios:8c66e78ea79aff973e160b',
    messagingSenderId: '495145618386',
    projectId: 'smart-64616',
    databaseURL: 'https://smart-64616-default-rtdb.firebaseio.com',
    storageBucket: 'smart-64616.appspot.com',
    iosBundleId: 'com.example.smartsavior2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhY-qfnE4HgV1ZGNLjqecN7WpeE0uCEj8',
    appId: '1:495145618386:web:395f278278df37383e160b',
    messagingSenderId: '495145618386',
    projectId: 'smart-64616',
    authDomain: 'smart-64616.firebaseapp.com',
    databaseURL: 'https://smart-64616-default-rtdb.firebaseio.com',
    storageBucket: 'smart-64616.appspot.com',
  );
}
